host: 0.0.0.0
port: 3333  # TODO: 環境に合わせて変更
threaded: true

access_control_allow_origin: '*'
access_control_allow_methods: 'GET, OPTIONS'
access_control_allow_headers: 'Content-Type, X-Requested-With, Authorization'
